name: AISOC Internship Workspace
description: Use this template to submit a project proposal for the AISOC internship program.
title: "AISOC Workspace: <Project Title>"
labels: ["aisoc", "proposal"]
assignees: []

body:
  - type: input
    id: project_title
    attributes:
      label: 🧠 Project Title
      description: Briefly describe the title of your project
      placeholder: RAG-based chatbot for Panjab University admission queries
    validations:
      required: true

  - type: textarea
    id: team_details
    attributes:
      label: 👥 Team Details
      description: Provide the team name, member names, and email addresses
      placeholder: |
        - Team Name: BotSquad
        - Member 1: Nishika Rawat – [nishikapnp2004@gmail.com]
        -Member 2: Nikhil Kaundal – [nikhilkaundal1257@gmail.com]
        -Member 3: Rhythm Pandey – [rhythmjk30@gmail.com]
        -Member 4: Manthan Dhiman – [dhimaan0011@gmail.com] 
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: 🧩 Problem Statement
      description: Briefly describe the problem your project aims to solve
      placeholder: The Panjab University (PU) website has a lot of admission-related information, but it is spread across many different pages and is not easy to find. New or interested students often get confused while searching for details like course options, eligibility, last dates, fees, or how to apply. Right now, there is no system or assistant that can help students quickly get clear and accurate answers to their questions. To solve this, we are building a smart AI chatbot that will use the RAG (Retrieval-Augmented Generation) method. This chatbot will understand the user’s questions and give answers based on real data from the PU website. It will help save time, reduce confusion, and make the admission process easier for both students and the university staff.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🚀 Motivation
      description: Explain the motivation or background behind choosing this project
      placeholder: What inspired your team to work on this project?
    validations:
      required: true

  - type: textarea
    id: expected_outcome
    attributes:
      label: 🎯 Expected Outcome
      description: List the expected outcomes from the project as bullet points
      placeholder: |
        - Functional AI chatbot interface
        - API integration with knowledge base
        - Documentation and user guide
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: 📅 Timeline & Milestones
      description: Provide a timeline with measurable milestones (e.g. weekly)
      placeholder: |
       -Week 1:	Finalize target URLs and initiate scraping via Playwright
       -Week 2:	Complete PDF scraping and store all data in .csv files
       -Week 3:	Clean and chunk data, create embeddings, and index with FAISS
       -Week 4:	Integrate with LLM via LlamaIndex and test chatbot functionality
       -Week 5:	Design UI, finalize chatbot, deploy, and prepare documentation

    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: 📦 Final Deliverables
      description: Describe the expected final deliverables at the end of the program
      placeholder: |
        - Working demo hosted on a public link
        - Codebase with proper documentation
        - Presentation explaining the solution
    validations:
      required: true

  - type: textarea
    id: appendix
    attributes:
      label: 📎 Appendix (Optional)
      description: Add any extra information, links, or references
      placeholder: |
        - GitHub repository link
        - Reference documents or datasets
        - Related prior work
    validations:
      required: false
